name: build

on: [push]

jobs:
  build:
    name: build
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        go-version: [1.17.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          - go-version: '1.17'
      - name: hello
        shell: bash
        env:
          SOURCE_FOLDER: cmd
          SOURCE_FILE_NAME: main.go
          OUTPUT_FILE_NAME: main
          DST_PATH: bin/
        run: |
          make build
