name: build

on: [push]

jobs:
  build:
    name: build
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        go-version: [1.17.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: hello
        shell: bash
        env:
          NAME: "World"
          GREETINGS_WORD: "Hello"
          EXCLAMATION_POINT: "!"
        run: |
          pwd
          ls -la
          make hello
