name: tests

on: [push]

jobs:
  tests:
    name: tests
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        go-version: [1.17.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - run: go version
      - name: tests
        shell: bash
        run: |
          make tests